const doctorSeedData = [
  {
    name: "Dr. Sarah Johnson",
    email: "doctor@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888888",
    location: "Delhi",
    specialization: "Cardiologist",
    experience: 8,
    fees: 1200,
    about: "Specialist in preventive cardiology and long-term heart care.",
    qualifications: ["MBBS", "MD Cardiology"],
    availabilitySlots: [
      { day: "Monday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
      { day: "Wednesday", startTime: "15:00", endTime: "18:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Priya Menon",
    email: "priya.menon@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888801",
    location: "Bengaluru",
    specialization: "Gynecologist",
    experience: 11,
    fees: 900,
    about: "Focuses on women's wellness, preventive screening, and reproductive health.",
    qualifications: ["MBBS", "MS Obstetrics & Gynaecology"],
    availabilitySlots: [
      { day: "Tuesday", startTime: "09:30", endTime: "12:30", maxPatients: 1 },
      { day: "Friday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Arjun Malhotra",
    email: "arjun.malhotra@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888802",
    location: "Mumbai",
    specialization: "Dermatologist",
    experience: 7,
    fees: 800,
    about: "Treats clinical dermatology concerns with a strong focus on patient education.",
    qualifications: ["MBBS", "MD Dermatology"],
    availabilitySlots: [
      { day: "Monday", startTime: "11:00", endTime: "14:00", maxPatients: 1 },
      { day: "Saturday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Neha Kapoor",
    email: "neha.kapoor@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888803",
    location: "Hyderabad",
    specialization: "Pediatrician",
    experience: 10,
    fees: 750,
    about: "Experienced in child development, preventive pediatrics, and routine care.",
    qualifications: ["MBBS", "MD Pediatrics"],
    availabilitySlots: [
      { day: "Wednesday", startTime: "09:00", endTime: "12:00", maxPatients: 1 },
      { day: "Saturday", startTime: "16:00", endTime: "19:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Rohan Iyer",
    email: "rohan.iyer@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888804",
    location: "Chennai",
    specialization: "Neurologist",
    experience: 13,
    fees: 1500,
    about: "Provides evidence-based neurological consultation for complex cases.",
    qualifications: ["MBBS", "DM Neurology"],
    availabilitySlots: [
      { day: "Thursday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
      { day: "Sunday", startTime: "09:00", endTime: "11:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Kavita Sharma",
    email: "kavita.sharma@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888805",
    location: "Pune",
    specialization: "Orthopedic Surgeon",
    experience: 9,
    fees: 1300,
    about: "Handles sports injuries, bone health, and joint mobility management.",
    qualifications: ["MBBS", "MS Orthopedics"],
    availabilitySlots: [
      { day: "Tuesday", startTime: "15:00", endTime: "18:00", maxPatients: 1 },
      { day: "Friday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Sameer Khan",
    email: "sameer.khan@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888806",
    location: "Kolkata",
    specialization: "ENT Specialist",
    experience: 6,
    fees: 700,
    about: "Consults on sinus, hearing, throat, and airway related conditions.",
    qualifications: ["MBBS", "MS ENT"],
    availabilitySlots: [
      { day: "Monday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
      { day: "Thursday", startTime: "09:30", endTime: "12:30", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Meera Nair",
    email: "meera.nair@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888807",
    location: "Kochi",
    specialization: "Psychiatrist",
    experience: 12,
    fees: 1100,
    about: "Offers compassionate and structured mental health consultations.",
    qualifications: ["MBBS", "MD Psychiatry"],
    availabilitySlots: [
      { day: "Wednesday", startTime: "13:00", endTime: "16:00", maxPatients: 1 },
      { day: "Saturday", startTime: "09:00", endTime: "12:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Vikram Sethi",
    email: "vikram.sethi@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888808",
    location: "Ahmedabad",
    specialization: "General Physician",
    experience: 14,
    fees: 600,
    about: "Primary care consultant with strong focus on chronic disease management.",
    qualifications: ["MBBS", "MD Internal Medicine"],
    availabilitySlots: [
      { day: "Tuesday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
      { day: "Sunday", startTime: "10:00", endTime: "12:00", maxPatients: 1 },
    ],
  },
  {
    name: "Dr. Ananya Bose",
    email: "ananya.bose@doctorbook.com",
    password: "Doctor@123",
    phone: "8888888809",
    location: "Jaipur",
    specialization: "Oncologist",
    experience: 15,
    fees: 1800,
    about: "Supports oncology patients with personalized consultation and long-term planning.",
    qualifications: ["MBBS", "DM Oncology"],
    availabilitySlots: [
      { day: "Friday", startTime: "11:00", endTime: "14:00", maxPatients: 1 },
      { day: "Saturday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
    ],
  },
];

module.exports = { doctorSeedData };
