const users = [
  {
    name: "Admin User",
    email: "admin@doctorbook.com",
    password: "Admin@123",
    role: "admin",
    phone: "9999999999",
    location: "Mumbai",
  },
  {
    name: "Dr. Sarah Johnson",
    email: "sarah@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888801",
    location: "Delhi",
  },
  {
    name: "Dr. Rajesh Kumar",
    email: "rajesh@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888802",
    location: "Mumbai",
  },
  {
    name: "Dr. Priya Nair",
    email: "priya@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888803",
    location: "Bengaluru",
  },
  {
    name: "Dr. Arjun Mehta",
    email: "arjun@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888804",
    location: "Hyderabad",
  },
  {
    name: "Dr. Kavitha Reddy",
    email: "kavitha@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888805",
    location: "Chennai",
  },
  {
    name: "Dr. Anil Verma",
    email: "anil@doctorbook.com",
    password: "Doctor@123",
    role: "doctor",
    phone: "8888888806",
    location: "Pune",
  },
  {
    name: "Amit Sharma",
    email: "patient@doctorbook.com",
    password: "Patient@123",
    role: "patient",
    phone: "7777777777",
    location: "Bengaluru",
  },
];

const doctorProfiles = [
  {
    email: "sarah@doctorbook.com",
    specialization: "Cardiology",
    experience: 12,
    fees: 1500,
    location: "Delhi",
    about: "Senior cardiologist with expertise in preventive care and interventional procedures. AIIMS trained with 12 years of practice.",
    qualifications: ["MBBS", "MD Cardiology", "DM Cardiology", "AIIMS Delhi"],
    availabilitySlots: [
      { day: "Monday",    startTime: "10:00", endTime: "13:00", maxPatients: 1 },
      { day: "Wednesday", startTime: "15:00", endTime: "18:00", maxPatients: 1 },
      { day: "Friday",    startTime: "10:00", endTime: "13:00", maxPatients: 1 },
    ],
  },
  {
    email: "rajesh@doctorbook.com",
    specialization: "Orthopedics",
    experience: 9,
    fees: 1200,
    location: "Mumbai",
    about: "Specializes in joint replacement and sports injuries. Over 1000 successful knee replacement surgeries.",
    qualifications: ["MBBS", "MS Orthopedics", "Fellowship in Joint Replacement"],
    availabilitySlots: [
      { day: "Tuesday",  startTime: "09:00", endTime: "12:00", maxPatients: 1 },
      { day: "Thursday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
      { day: "Saturday", startTime: "10:00", endTime: "13:00", maxPatients: 1 },
    ],
  },
  {
    email: "priya@doctorbook.com",
    specialization: "Gynecology",
    experience: 11,
    fees: 1000,
    location: "Bengaluru",
    about: "Dedicated to women's health across all life stages. Specializes in high-risk pregnancies and laparoscopic surgery.",
    qualifications: ["MBBS", "MD Obstetrics & Gynaecology", "Fellowship in Reproductive Medicine"],
    availabilitySlots: [
      { day: "Monday",    startTime: "09:00", endTime: "12:00", maxPatients: 1 },
      { day: "Wednesday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
      { day: "Friday",    startTime: "09:00", endTime: "12:00", maxPatients: 1 },
    ],
  },
  {
    email: "arjun@doctorbook.com",
    specialization: "Neurology",
    experience: 15,
    fees: 2000,
    location: "Hyderabad",
    about: "Expert in epilepsy, stroke, and neurodegenerative diseases. Trained at NIMHANS Bengaluru.",
    qualifications: ["MBBS", "MD General Medicine", "DM Neurology", "NIMHANS"],
    availabilitySlots: [
      { day: "Tuesday",  startTime: "11:00", endTime: "14:00", maxPatients: 1 },
      { day: "Thursday", startTime: "16:00", endTime: "19:00", maxPatients: 1 },
    ],
  },
  {
    email: "kavitha@doctorbook.com",
    specialization: "Dermatology",
    experience: 7,
    fees: 800,
    location: "Chennai",
    about: "Expert in cosmetic dermatology, skin diseases, and laser treatments. Friendly and patient-focused approach.",
    qualifications: ["MBBS", "MD Dermatology", "DNB Dermatology"],
    availabilitySlots: [
      { day: "Monday",    startTime: "10:00", endTime: "13:00", maxPatients: 1 },
      { day: "Thursday",  startTime: "14:00", endTime: "17:00", maxPatients: 1 },
      { day: "Saturday",  startTime: "09:00", endTime: "12:00", maxPatients: 1 },
    ],
  },
  {
    email: "anil@doctorbook.com",
    specialization: "Pediatrics",
    experience: 10,
    fees: 700,
    location: "Pune",
    about: "Child health specialist with expertise in newborn care, childhood infections, and developmental disorders.",
    qualifications: ["MBBS", "MD Pediatrics", "Fellowship in Neonatal Care"],
    availabilitySlots: [
      { day: "Monday",   startTime: "09:00", endTime: "12:00", maxPatients: 1 },
      { day: "Wednesday", startTime: "14:00", endTime: "17:00", maxPatients: 1 },
      { day: "Friday",   startTime: "09:00", endTime: "11:00", maxPatients: 1 },
    ],
  },
];

module.exports = { users, doctorProfiles };
